language: node_js
node_js:
  - '8'
cache:
  directories:
    - ~/.npm
    - "node_modules"
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
